// Generated by CoffeeScript 1.7.1
(function() {
  var getHelpText, optimist, options, packageData;

  optimist = require('optimist');

  options = require('./options');

  packageData = require('../../package.json');

  getHelpText = function() {
    options.forEach(function(_arg) {
      var defaultValue, desc, name;
      name = _arg.name, desc = _arg.desc, defaultValue = _arg.defaultValue;
      return optimist.describe(name, desc);
    });
    optimist.usage(packageData.description).describe("version", "Print the current version number").describe("help", "Show this help message").alias("version", "v").alias("help", "h");
    return optimist.help().split('\n').map(function(x) {
      return x.trimRight();
    }).join('\n');
  };

  exports.binaryMeta = function(type, output, callback) {
    var help;
    packageData = require('../../package.json');
    help = require('../implementation/help');
    if (type === 'help') {
      return output.write(getHelpText() + '\n');
    } else if (type === 'version') {
      return output.write(packageData.version + '\n');
    } else {
      return callback();
    }
  };

}).call(this);
