// Generated by CoffeeScript 1.7.1
(function() {
  var AWS, config, deploy, path, _;

  path = require('path');

  _ = require('underscore');

  AWS = require('aws-sdk');

  deploy = require('../implementation/deploy');

  config = require('../implementation/load-config');

  exports.load = config.createLoader({
    loadPlugin: function(plugin) {
      return require('../../../' + plugin);
    },
    userConfigPath: path.resolve(process.env.HOME, ".bucketful")
  });

  exports.deploy = function(options, callback) {
    var finalConf;
    finalConf = _.extend({}, options, {
      createAwsClient: function(_arg) {
        var key, region, secret;
        region = _arg.region, key = _arg.key, secret = _arg.secret;
        AWS.config.update({
          region: region,
          accessKeyId: key,
          secretAccessKey: secret
        });
        return new AWS.S3().client;
      }
    });
    return deploy(finalConf, callback);
  };

}).call(this);
