// Generated by CoffeeScript 1.7.1
(function() {
  var bucketful, help, optimist, type;

  process.on('uncaughtException', function(err) {
    return console.log('Uncaught exception!', (err != null ? err.message : void 0) || err);
  });

  optimist = require('optimist');

  bucketful = require('./api');

  help = require('../implementation/help');

  if (optimist.argv.help) {
    type = 'help';
  }

  if (optimist.argv.version) {
    type = 'version';
  }

  help.binaryMeta(type, process.stdout, function() {
    var conf;
    conf = bucketful.load();
    conf.output = process.stdout;
    return bucketful.deploy(conf, function(err) {
      console.log();
      if (err) {
        console.log(err);
        return process.exit(1);
      }
    });
  });

}).call(this);
